### ISSUE TITLE
Remove cleanupSome docs from MDN

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-cleanup-some#6]
cleanupSome is documented at https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry/cleanupSome . This should be removed from MDN as part of splitting cleanupSome into a separate Stage 2 proposal.

**Comment by littledan** [comment]
cc @tjcrowder

**Comment by tjcrowder** [comment]
@littledan - All done! Page is deleted, link to it removed from the `FinalizationRegistry` page, and I've done a PR to remove the compat data.

**Comment by littledan** [comment]
Thanks @tjcrowder !
